[package]
name = "trane-rustlings"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
indoc = "1.0"
trane = "0.2.3"

[dev-dependencies]
tempfile = "3.3.0"

# Commented out for use for local development.
# trane = { path = "../trane" }